# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  node: 18.16.1

repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
      - id: eslint
        language: node
        args: [--fix, --config, ./.eslintrc.json]
        files: \.tsx?$
        types: [file]
        additional_dependencies:
          - eslint
          - eslint-config-prettier
          - eslint-plugin-eslint-comments
          - eslint-plugin-jest
          - eslint-plugin-prettier
          - eslint-plugin-react
          - eslint-plugin-react-hooks
          - eslint-plugin-simple-import-sort
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'
          - jest
