export const coursesData = [
  {
    imageSrc: '/images/card1.svg',
    imageAlt: 'Course Image 1',
    title: 'Table Top Exercises',
    description:
      'This course provides essential cybersecurity training for enthusiasts transitioning into the field, emphasizing CIA principles and continuous protection of information and systems for business objectives.',
    buttonText: 'View Course',
    isComingSoon: true,
  },
  {
    imageSrc: '/images/card1.svg',
    imageAlt: 'Course Image 2',
    title: 'Incident Response Training',
    description:
      'Learn the essential steps and strategies for effective incident response in a cybersecurity context.',
    buttonText: 'View Course',
    isComingSoon: true,
  },
  {
    imageSrc: '/images/card1.svg',
    imageAlt: 'Course Image 3',
    title: 'Network Security Fundamentals',
    description:
      'Understand the basics of network security, including firewalls, VPNs, and intrusion detection systems.',
    buttonText: 'View Course',
    isComingSoon: false,
  },
  {
    imageSrc: '/images/card1.svg',
    imageAlt: 'Course Image 4',
    title: 'Penetration Testing Techniques',
    description:
      'Learn the various penetration testing methodologies and tools to assess the security of systems and networks.',
    buttonText: 'View Course',
    isComingSoon: true,
  },
  {
    imageSrc: '/images/card1.svg',
    imageAlt: 'Course Image 5',
    title: 'Cloud Security Best Practices',
    description:
      'This course provides essential cybersecurity training for enthusiasts transitioning into the field, emphasizing CIA principles and continuous protection of information and systems for business objectives.',
    buttonText: 'View Course',
    isComingSoon: false,
  },
];

export const Tabledatas = [
  {
    paymentId: '2HJ3SBN4F443',
    date: '29th May 2021',
    course: 'Cyber Security Fundamentals & Cloud Security Best Practices',
    status: 'paid',
    amount: '299393',
  },
  {
    paymentId: '5JH7NML6R688',
    date: '10th June 2021',
    course: 'Network Security',
    status: 'unpaid',
    amount: '199993',
  },
  {
    paymentId: '9KL4PQO1V123',
    date: '15th July 2021',
    course: 'Penetration Testing Techniques',
    status: 'paid',
    amount: '399393',
  },
  {
    paymentId: '3BC8VTR3E456',
    date: '20th August 2021',
    course: 'Cloud Security Best Practices',
    status: 'pending',
    amount: '499393',
  },
  {
    paymentId: '7WQ2XDE9T789',
    date: '25th September 2021',
    course: 'Incident Response Training',
    status: 'paid',
    amount: '599393',
  },
  {
    paymentId: '1ZN9LBV8Q321',
    date: '5th October 2021',
    course: 'Advanced Threat Hunting',
    status: 'unpaid',
    amount: '699393',
  },
  {
    paymentId: '6DJ4KLP2V222',
    date: '12th November 2021',
    course: 'Digital Forensics and Incident Response',
    status: 'paid',
    amount: '799393',
  },
  {
    paymentId: '3PL2HRT5F432',
    date: '20th December 2021',
    course: 'Network Security Monitoring',
    status: 'pending',
    amount: '899393',
  },
  {
    paymentId: '8KF1NPL8D555',
    date: '15th January 2022',
    course: 'Ethical Hacking',
    status: 'paid',
    amount: '999393',
  },
  {
    paymentId: '4BH7VTR1E234',
    date: '22nd February 2022',
    course: 'Cyber Threat Intelligence',
    status: 'unpaid',
    amount: '1099393',
  },
  {
    paymentId: '7WS6YDF4T678',
    date: '30th March 2022',
    course: 'Mobile Security',
    status: 'paid',
    amount: '1199393',
  },
  {
    paymentId: '2GH3XNM9V432',
    date: '10th April 2022',
    course: 'Web Application Security',
    status: 'pending',
    amount: '1299393',
  },
  {
    paymentId: '5JK9LMT2R123',
    date: '18th May 2022',
    course: 'Cybersecurity Risk Management',
    status: 'paid',
    amount: '1399393',
  },
  {
    paymentId: '9LM2PQO3V678',
    date: '25th June 2022',
    course: 'Advanced Penetration Testing',
    status: 'unpaid',
    amount: '1499393',
  },
  {
    paymentId: '3DC5VTR8E789',
    date: '3rd July 2022',
    course: 'Blockchain Security',
    status: 'paid',
    amount: '1599393',
  },
  {
    paymentId: '8MQ7XDE5T234',
    date: '12th August 2022',
    course: 'IoT Security',
    status: 'pending',
    amount: '1699393',
  },
  {
    paymentId: '4PB3LNV7Q876',
    date: '20th September 2022',
    course: 'Cryptography',
    status: 'paid',
    amount: '1799393',
  },
  {
    paymentId: '1ZN5HRT6F123',
    date: '28th October 2022',
    course: 'Malware Analysis',
    status: 'unpaid',
    amount: '1899393',
  },
  {
    paymentId: '6DJ1NPL2V567',
    date: '5th November 2022',
    course: 'Threat Modeling',
    status: 'paid',
    amount: '1999393',
  },
  {
    paymentId: '3PL9VTR5E890',
    date: '12th December 2022',
    course: 'Cloud Security Architecture',
    status: 'pending',
    amount: '2099393',
  },
];
